#!/bin/bash

checkExitCode() {
if [ $? -ne 0 ]; then
    echo "Error"
    exit 1;
fi
}

BASEDIR=`dirname $0`

. $BASEDIR/io.sh 2 1 1 "$@"

START_YEAR=`date +"%Y" -d "$PARAMS1"`

python3 $BASEDIR/cycles_to_crop_fertilizer_multiple_points.py $START_YEAR $INPUTS2 $OUTPUTS1
checkExitCode
