#!/bin/bash

unset http_proxy

checkExitCode() {
if [ $? -ne 0 ]; then
    echo "Error"
    exit 1;
fi
}

BASEDIR=`dirname $0`

. $BASEDIR/io.sh 9 3 23 "$@"

# project name
PROJECT_NAME=$PARAMS3

# untar PIHM-base
tar -zxvf $INPUTS9

# move input data into PIHM-base folder
mv $INPUTS1 PIHM-base/$PROJECT_NAME.att
mv $INPUTS2 PIHM-base/$PROJECT_NAME.forc
mv $INPUTS4 PIHM-base/$PROJECT_NAME.soil
mv $INPUTS5 PIHM-base/$PROJECT_NAME.riv
mv $INPUTS6 PIHM-base/$PROJECT_NAME.geol
mv $INPUTS7 PIHM-base/$PROJECT_NAME.ibc
mv $INPUTS8 PIHM-base/$PROJECT_NAME.lc

# untar Model Info and move into PIHM-base folder
tar -zxvf $INPUTS3
mv ModelInfo PIHM-base/

# set total number of days
DAYS=$(( (($(date -d $PARAMS2 +%s) - $(date -d $PARAMS1 +%s)) / (24*3600) + 1 ) * 1440 ))
perl -p -i -e "s/0	525600	0/0	$DAYS	0/" PIHM-base/$PROJECT_NAME.para

# run the model
cd PIHM-base &&/usr/bin/pihm $PROJECT_NAME 2>&1
checkExitCode

# prepare output data
cd ..
mv PIHM-base/$PROJECT_NAME.GW       $OUTPUTS1
mv PIHM-base/$PROJECT_NAME.infil    $OUTPUTS2
mv PIHM-base/$PROJECT_NAME.is       $OUTPUTS3
mv PIHM-base/$PROJECT_NAME.snow     $OUTPUTS4
mv PIHM-base/$PROJECT_NAME.surf     $OUTPUTS5
mv PIHM-base/$PROJECT_NAME.unsat    $OUTPUTS6
mv PIHM-base/$PROJECT_NAME.et0      $OUTPUTS7
mv PIHM-base/$PROJECT_NAME.et1      $OUTPUTS8
mv PIHM-base/$PROJECT_NAME.et2      $OUTPUTS9
mv PIHM-base/$PROJECT_NAME.Rech     $OUTPUTS10
mv PIHM-base/$PROJECT_NAME.stage    $OUTPUTS11
mv PIHM-base/$PROJECT_NAME.rbed     $OUTPUTS12
mv PIHM-base/$PROJECT_NAME.rivFlx0  $OUTPUTS13
mv PIHM-base/$PROJECT_NAME.rivFlx1  $OUTPUTS14
mv PIHM-base/$PROJECT_NAME.rivFlx2  $OUTPUTS15
mv PIHM-base/$PROJECT_NAME.rivFlx3  $OUTPUTS16
mv PIHM-base/$PROJECT_NAME.rivFlx4  $OUTPUTS17
mv PIHM-base/$PROJECT_NAME.rivFlx5  $OUTPUTS18
mv PIHM-base/$PROJECT_NAME.rivFlx6  $OUTPUTS19
mv PIHM-base/$PROJECT_NAME.rivFlx7  $OUTPUTS20
mv PIHM-base/$PROJECT_NAME.rivFlx8  $OUTPUTS21
mv PIHM-base/$PROJECT_NAME.rivFlx9  $OUTPUTS22
mv PIHM-base/$PROJECT_NAME.rivFlx10 $OUTPUTS23
