#!/bin/bash

unset http_proxy

checkExitCode() {
if [ $? -ne 0 ]; then
    echo "Error"
    exit 1;
fi
}

BASEDIR=`dirname $0`

. $BASEDIR/io.sh 3 8 10 "$@"

# create Cycles input folder and move base files
mkdir -p input
mv $INPUTS1 input/
mv $INPUTS2 input/
mv $INPUTS3 input/

# run cycles
python3 cycles-wrapper.py --start-year $PARAMS1 --end-year $PARAMS2 --baseline True --crop $PARAMS3 --start-planting-date $PARAMS4 --end-planting-date $PARAMS5 --fertilizer-rate $PARAMS6 --weed-fraction $PARAMS7 --forcing $PARAMS8 --weather-file $INPUTS1 $INPUTS3 $INPUTS2
checkExitCode

# IMPORTANT: temporary hack for saving input/output data into local folder
mkdir outputs
cp -R input/ outputs/
cp -R output/ outputs/
zip -r outputs.zip outputs/
mv outputs.zip $OUTPUTS9

# moving and renaming output data
mv output/cycles-run/annualSoilProfileC.dat $OUTPUTS1
mv output/cycles-run/annualSOM.dat $OUTPUTS2
mv output/cycles-run/$PARAMS3.dat $OUTPUTS3
mv output/cycles-run/N.dat $OUTPUTS4
mv output/cycles-run/season.dat $OUTPUTS5
mv output/cycles-run/summary.dat $OUTPUTS6
mv output/cycles-run/weather.dat $OUTPUTS7
mv output/cycles-run/water.dat $OUTPUTS8
mv output/cycles-run/reinit.dat $OUTPUTS10
