#!/bin/bash

checkExitCode() {
if [ $? -ne 0 ]; then
    echo "Error"
    exit 1;
fi
}

BASEDIR=`dirname $0`

. $BASEDIR/io.sh 1 2 1 "$@"

START_YEAR=`date +"%Y" -d "$PARAMS1"`

python3 $BASEDIR/economic_to_vis.py $START_YEAR $PARAMS2 $INPUTS1 $OUTPUTS1
checkExitCode
