#!/bin/bash

checkExitCode() {
if [ $? -ne 0 ]; then
    echo "Error"
    exit 1;
fi
}

BASEDIR=`dirname $0`

. $BASEDIR/io.sh 6 17 2 "$@"

set -x


# Inputs
mv $INPUTS1 alldata.csv
mv $INPUTS2 lvardata.csv
mv $INPUTS3 fvardata.csv
mv $INPUTS4 fertdata.csv
mv $INPUTS5 cyclesdata.csv
mv $INPUTS6 etadata.csv

generate_percent.py $PARAMS1 $PARAMS2 $PARAMS3 $PARAMS4 $PARAMS5 $PARAMS6 $PARAMS7 $PARAMS8 $PARAMS9 $PARAMS10 $PARAMS11 $PARAMS12 $PARAMS13 $PARAMS14 $PARAMS15

generate_sim.py alldata.csv $PARAMS16 $PARAMS17

# Economic Model
gams MINT_v8.gms
EC=$?
if [ $EC -ne 0 ]; then
    cat MINT_V8.lst 1>&2
	exit $EC
fi


# Outputs
mv MINT_econ_simulation.txt $OUTPUTS1
mv MINT_econ_calibration.txt $OUTPUTS2
