#!/bin/bash

checkExitCode() {
if [ $? -ne 0 ]; then
    echo "Error"
    exit 1;
fi
}

BASEDIR=`dirname $0`

. $BASEDIR/io.sh 3 0 1 "$@"

python3 cycles-to-crop.py $INPUTS1 $INPUTS2 $OUTPUTS1
checkExitCode

