#!/bin/bash

checkExitCode() {
if [ $? -ne 0 ]; then
    echo "Error"
    exit 1;
fi
}

BASEDIR=`dirname $0`

. $BASEDIR/io.sh 2 1 1 "$@"

START_YEAR=`date +"%Y" -d "$PARAMS1"`

python3 cycles-to-crop.py $START_YEAR $INPUTS1 $OUTPUTS1
checkExitCode
